import { fileURLToPath } from 'node:url';

import { defineConfig } from 'vitest/config';

/**
 * Frontend unit tests. Kept separate from vite.config.ts on purpose: that config
 * loads the Laravel/Wayfinder plugins, which shell out to artisan and are not
 * wanted (nor needed) for plain TypeScript units.
 */
export default defineConfig({
    test: {
        environment: 'jsdom',
        include: ['tests/js/**/*.test.ts'],
    },
    resolve: {
        alias: [
            // `resources/js/routes` is generated by Wayfinder and gitignored, so
            // route helpers resolve to a stub — the suite then runs anywhere,
            // with no artisan step first.
            {
                find: /^@\/routes\/(.*)$/,
                replacement: fileURLToPath(
                    new URL('./tests/js/stubs/routes/$1', import.meta.url),
                ),
            },
            {
                find: '@',
                replacement: fileURLToPath(
                    new URL('./resources/js', import.meta.url),
                ),
            },
        ],
    },
});
